runtime: java
vm: True
instance_class: F1
threadsafe: True
auto_id_policy: default
env_variables:
  'serverURL': 'http://YOUR_PROJECT_.appspot.com'
  'googleKey': 'xxxxxxxxxxxxxxxxxx.apps.googleusercontent.com'
  'googleSecret': 'xxxxxxxxxxxxxxxxxx'
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

beta_settings:
  'java_quickstart': 'true'
health_check:
  enable_health_check: True
api_version: 'none'
handlers:

- url: (/assets/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional

- url: /
  script: unused
  login: optional
  secure: always

- url: /.*
  script: unused
  login: optional
  secure: always

- url: /application/.*
  script: IGNORED
  secure: always

- url: /api/.*
  script: IGNORED
  secure: always

- url: /oauth/.*
  script: IGNORED
  secure: always
