runtime: custom
vm: True
instance_class: F1
threadsafe: True
auto_id_policy: default
env_variables:
  'serverURL': 'https://your-project-here.appspot.com'
beta_settings:
  'java_quickstart': 'true'
health_check:
  enable_health_check: True
api_version: 'none'
handlers:

- url: (/assets/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional

- url: /
  script: unused
  login: optional
  secure: always

- url: /.*
  script: unused
  login: optional
  secure: always

- url: /application/.*
  script: IGNORED
  secure: always

- url: /api/.*
  script: IGNORED
  secure: always

- url: /oauth/.*
  script: IGNORED
  secure: always
